### ISSUE TITLE
How is the magnetic susceptibility Xi defined

### ISSUE THREAD

**Issue by leeoral** [magpylib/magpylib-material-response#1]
Hi. Can you please provide more information of how "Xi" is defined (or a reference) when computing the magnetic field in the presence of demagnetization. I am wanting to extract this information from the magnet datasheets.

Thanks!

**Comment by fslanovc** [comment]
It is the local magnetic susceptibility χ around the remanence magnetization M_r. If you define the magnetization M_r and the susceptibility χ, then the magnetic field H is calculated and the resulting magnetization results in M = M_r + χ * H.
Then value is then the new magnetization.
